name: CICD

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

env:
  CI_CD_AS1_DEVOPS: ${{ secrets.CI_CD_AS1_DEVOPS }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: ./build
      - run: echo "Build da aplicação feito com sucesso!"
      
  test-job:
    name: Test
    needs: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node ./src/test.js
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "nodejs"

  deploy-job:
    name: Deploy
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-files
          path: ./build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ env.CI_CD_AS1_DEVOPS }}
          publish_dir: ./build
      - name: Get code
        uses: actions/checkout@v4
      - name: Notificate via Telegram
        run: |
          chmod 745 ./bot_telegram.sh
          ./bot_telegram.sh
      - name: closing
        run: echo "Deploy Finalizado!"

  push-image-to-docker-hub-job:
    name: Push Image to Docker Hub
    needs: deploy-job
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: hdelavidaum/pucpr-as2:latest